spring:
  datasource:
    url: jdbc:mysql://localhost:3306/assign-1.1
    username: root
    password: Yaswanth@1994
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 #maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior.
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  batch:
    initialize-schema: ALWAYS
  application:
      name: FeignClient
      
file:
  input: 
    teacher: teacher.csv
    course: course.csv
    student: student.csv
    
jwt: 
  secret: 1@3$5^7*9)0(8&6%42!
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
        